version: 2
jobs:
  build:
    docker:
      - image: debian:stretch-slim
    working_directory: /go/src/github.com/project/repo
    steps:
      - setup_remote_docker:
          version: 17.11.0-ce
          docker_layer_caching: true
      - checkout
      - run:
          name: Test
          command: echo $DOCKER_USERNAME
